name: Minarca-client

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  RELEASE_TAG: 6.1.0a3

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python2 librsync-dev libacl1-dev git xvfb xauth cron zenity kdialog -y

      - name: Install tox
        run: pip install tox

      - name: Clone minarca client
        run: |
          git clone https://gitlab.com/ikus-soft/minarca.git
          cd minarca
          git checkout ${{ env.RELEASE_TAG }}

      - name: Patch minarca client for arm64
        run: |
          cd minarca
          sed -i "s/architecture='amd64'/architecture='arm64'/g" packaging/minarca.spec
          sed -i '/^\s*import os\s*$/d' minarca_client/core/notification/tests/test_notification.py
          sed -i "s|NO_DBUS = not os.environ.get('DBUS_SESSION_BUS_ADDRESS', False)|NO_DBUS = True|" minarca_client/core/notification/tests/test_notification.py

      - name: Build and run tests
        run: |
          cd minarca
          tox -e flake8,black,isort
          tox -e py3-linux
        
      - name: Build package
        run: |
          cd minarca
          tox -e pyinstaller-linux
          mv dist/minarca-client_*_arm64.deb dist/minarca-client_${{ env.RELEASE_TAG }}_arm64.deb

      - name: Upload to GitHub Release
        uses: actions/upload-artifact@v4
        with:
          name: minarca-client_${{ env.RELEASE_TAG }}_arm64.deb
          path: minarca/dist/minarca-client_${{ env.RELEASE_TAG }}_arm64.deb

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
